name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devops

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra_changed }}
      api_changed: ${{ steps.filter.outputs.api_changed }}
      web_changed: ${{ steps.filter.outputs.web_changed }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/filter_action
        id: filter

  deploy-infra:
    needs: determine-changes
    if: needs.determine-changes.outputs.infra_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Deploy Infrastructure
        run: echo "Deploying infrastructure..."
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy ACR
        id: deploy-acr
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          scope: resourcegroup
          template: infra/acr.bicep
          failOnStdErr: false
      - name: Deploy ACI
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          scope: resourcegroup
          template: infra/aci.bicep
          failOnStdErr: false
          parameters: |
            server=${{ steps.deploy-acr.outputs.acrLoginServer }}

  build-images:
    needs: determine-changes
    if: needs.determine-changes.outputs.api_changed == 'true' || needs.determine-changes.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR
        run: |
          az acr login --name ${{ vars.ACR_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/Web/Dockerfile
          push: true
          tags: ${{ vars.ACR_NAME }}.azurecr.io/eshoponweb:latest
          context: .
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}
      - name: Deploy ACI
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          scope: resourcegroup
          template: infra/aci.bicep
          failOnStdErr: false
          parameters: |
            server=${{ vars.ACR_NAME }}.azurecr.io
            image=${{ vars.ACR_NAME }}.azurecr.io/eshoponweb:latest
